version: '3'
services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - minio
  minio:
    image: minio/minio
    command: server /data
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    ports:
      - "9000:9000"
    volumes:
      - ./data:/data
